CREATE TABLE sibyl_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(128) NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'ADMIN',
    must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sibyl_organization (
    id SMALLINT PRIMARY KEY CHECK (id = 1),
    organization VARCHAR(80) NOT NULL DEFAULT 'Sibyl System',
    language VARCHAR(8) NOT NULL DEFAULT 'de',
    timezone VARCHAR(64) NOT NULL DEFAULT 'Europe/Berlin',
    accent VARCHAR(16) NOT NULL DEFAULT 'classic',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sibyl_organization (id, organization) VALUES (1, 'Sibyl System');

CREATE TABLE sibyl_addon_settings (
    addon_id VARCHAR(120) PRIMARY KEY,
    settings_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sibyl_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(80) NOT NULL,
    action VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_sibyl_audit_created ON sibyl_audit_events (created_at DESC);
